[package]
name = "grapher"
version = "0.1.1"
authors = ["Akari202 <akaritwo0two@gmail.com>"]
edition = "2021"

[dependencies]
log = "0.4.21"
env_logger = "0.11.3"
sdl2 = { version = "0.36.0", features = ["ttf"] }
rayon = "1.10.0"
rand = "0.9.0-alpha.1"
rodio = "0.17.3"
